"""
Database integration for GeneTech genetic part availability checks.

This file does not connect to a traditional SQL database. Instead, it acts as
the database/registry layer for the project:

1. Read the generated circuits from circuits.txt.
2. Pull out every biological part name used in those circuits.
3. Convert each GeneTech part name into an external registry ID.
4. Check those IDs against configured registry providers.
5. Save a JSON report explaining which parts and circuits are buildable.
"""

from __future__ import annotations

import csv
import json
import sys
from dataclasses import dataclass
from datetime import datetime
from pathlib import Path
from typing import Dict, Iterable, List, Optional

import requests


# Folder that contains the app resources. In a PyInstaller macOS app, Python
# modules live under Contents/Frameworks while bundled data lives in Resources.
if getattr(sys, "frozen", False):
    BASE_DIR = Path(sys.executable).resolve().parents[1] / "Resources"
    APP_DATA_DIR = Path.home() / "Library" / "Application Support" / "GeneTechAI"
else:
    BASE_DIR = Path(__file__).resolve().parent
    APP_DATA_DIR = BASE_DIR

APP_DATA_DIR.mkdir(parents=True, exist_ok=True)

# Default circuit file generated by the GeneTech pipeline.
CIRCUITS_FILE = APP_DATA_DIR / "circuits.txt"

# CSV file that maps GeneTech's internal part names to iGEM part IDs.
PART_MAPPINGS_FILE = BASE_DIR / "part_mappings.csv"

# Folder where timestamped JSON reports are written after each database check.
REPORTS_DIR = APP_DATA_DIR / "database_reports"

# Create the report folder automatically if it does not already exist.
REPORTS_DIR.mkdir(parents=True, exist_ok=True)


@dataclass
class PartAvailability:
    """
    Simple container for the final availability decision for one biological part.

    Example: after checking PTac, this object stores that PTac maps to
    BBa_K864500, is a promoter, was found in the iGEM local catalog, and has
    an iGEM URL.
    """

    # GeneTech part name, such as PTac, PhlF, PBad, or YFP.
    part: str

    # Biological category, such as promoter, cds, rbs, reporter, or terminator.
    part_type: str

    # External registry ID, usually an iGEM ID like BBa_K864500.
    registry_id: Optional[str]

    # Name of the registry/provider that supplied the winning result.
    registry_name: Optional[str]

    # True means the part was found in at least one configured provider.
    available: bool

    # Explains where the result came from, such as local_catalog or mapping.
    source: str

    # Human-readable description of the biological part.
    description: str = ""

    # Link to the registry page for the part.
    url: str = ""

    # Explanation used when the part is not available.
    reason: str = ""

    def to_legacy_dict(self) -> dict:
        # The GUI expects dictionary-style data, so this converts the dataclass
        # into the older dictionary format used by the rest of the app.
        payload = {
            "part": self.part,
            "type": self.part_type,
            "available": self.available,
            "reason": self.reason,
        }

        # Only include optional fields when they have actual values. This keeps
        # the report cleaner and avoids empty registry fields for unmapped parts.
        if self.registry_id:
            payload["igem_id"] = self.registry_id
        if self.url:
            payload["url"] = self.url
        if self.description:
            payload["description"] = self.description
        payload["source"] = self.source
        payload["registry_name"] = self.registry_name
        return payload


class PartMapper:
    """
    Maps GeneTech parts to registry identifiers.

    This is the translation table between the part names GeneTech writes into
    circuits.txt and the public part IDs used by registries like iGEM.
    """

    # Built-in fallback mapping. These entries are always available even if the
    # CSV file is missing or broken.
    DEFAULT_PARTS = {
        "PTac": {
            "registry_id": "BBa_K864500",
            "part_type": "promoter",
            "description": "Tac promoter",
        },
        "PTet": {
            "registry_id": "BBa_R0040",
            "part_type": "promoter",
            "description": "TetR repressible promoter",
        },
        "PBad": {
            "registry_id": "BBa_I0500",
            "part_type": "promoter",
            "description": "Arabinose promoter",
        },
        "PAmtR": {
            "registry_id": "BBa_K1372007",
            "part_type": "promoter",
            "description": "AmtR repressible promoter",
        },
        "PAmeR": {
            "registry_id": "BBa_K1372008",
            "part_type": "promoter",
            "description": "AmeR repressible promoter",
        },
        "PHlYllR": {
            "registry_id": "BBa_K1372009",
            "part_type": "promoter",
            "description": "HlyIIR repressible promoter",
        },
        "PSrpR": {
            "registry_id": "BBa_K1372010",
            "part_type": "promoter",
            "description": "SrpR repressible promoter",
        },
        "PPhlF": {
            "registry_id": "BBa_K1372011",
            "part_type": "promoter",
            "description": "PhlF repressible promoter",
        },
        "PBM3R1": {
            "registry_id": "BBa_K1372012",
            "part_type": "promoter",
            "description": "BM3R1 repressible promoter",
        },
        "PBetl": {
            "registry_id": "BBa_K1372013",
            "part_type": "promoter",
            "description": "BetI repressible promoter",
        },
        "AmtR": {
            "registry_id": "BBa_K1372001",
            "part_type": "cds",
            "description": "AmtR repressor",
        },
        "AmeR": {
            "registry_id": "BBa_K1372002",
            "part_type": "cds",
            "description": "AmeR repressor",
        },
        "HlYllR": {
            "registry_id": "BBa_K1372003",
            "part_type": "cds",
            "description": "HlyIIR repressor",
        },
        "SrpR": {
            "registry_id": "BBa_K1372004",
            "part_type": "cds",
            "description": "SrpR repressor",
        },
        "PhlF": {
            "registry_id": "BBa_K1372005",
            "part_type": "cds",
            "description": "PhlF repressor",
        },
        "BM3R1": {
            "registry_id": "BBa_K1372006",
            "part_type": "cds",
            "description": "BM3R1 repressor",
        },
        "Betl": {
            "registry_id": "BBa_K1372014",
            "part_type": "cds",
            "description": "BetI repressor",
        },
        "YFP": {
            "registry_id": "BBa_E0030",
            "part_type": "reporter",
            "description": "YFP reporter",
        },
        "ECK120033737": {
            "registry_id": "BBa_B0015",
            "part_type": "terminator",
            "description": "Double terminator",
        },
    }

    # Several RBS labels in GeneTech all point to the same common iGEM RBS.
    DEFAULT_RBS_ID = "BBa_B0034"

    def __init__(self, csv_path: Path = PART_MAPPINGS_FILE):
        # Store the CSV path so this mapper knows where to look for overrides.
        self.csv_path = Path(csv_path)

        # Main dictionary used for lookups. Keys are GeneTech names like PTac;
        # values hold registry_id, part_type, and description.
        self.mapping: Dict[str, dict] = {}

        # First load the safe built-in mappings.
        self._load_defaults()

        # Then load the CSV mappings. CSV values can add to or override defaults.
        self._load_from_csv()

    def _load_defaults(self):
        # Copy every built-in mapping so later CSV edits do not mutate the class
        # constant DEFAULT_PARTS directly.
        self.mapping = {part: info.copy() for part, info in self.DEFAULT_PARTS.items()}

        # Add shorthand RBS parts that are not listed one-by-one in DEFAULT_PARTS.
        for rbs in ["A1", "F1", "H1", "S1", "P1", "B1", "E1"]:
            self.mapping[rbs] = {
                "registry_id": self.DEFAULT_RBS_ID,
                "part_type": "rbs",
                "description": "Ribosome binding site",
            }

    def _load_from_csv(self):
        # If part_mappings.csv is not present, the app still works because the
        # built-in defaults were already loaded.
        if not self.csv_path.exists():
            return

        try:
            # Read the CSV as named columns: genetech_part, igem_id, type, description.
            with self.csv_path.open("r", newline="") as handle:
                reader = csv.DictReader(handle)
                for row in reader:
                    # Pull the GeneTech part name and external registry ID from
                    # the current CSV row.
                    part = row.get("genetech_part", "").strip()
                    registry_id = row.get("igem_id", "").strip()

                    # Skip incomplete rows because they cannot be used for lookups.
                    if not part or not registry_id:
                        continue

                    # Add or replace the mapping for this GeneTech part.
                    self.mapping[part] = {
                        "registry_id": registry_id,
                        "part_type": row.get("type", "").strip() or self.get_part_type(part),
                        "description": row.get("description", "").strip(),
                    }
        except Exception:
            # Fall back to baked-in mappings if the CSV is malformed.
            pass

    def get_registry_id(self, part: str) -> Optional[str]:
        # Look up the part in the mapping table and return its registry ID.
        entry = self.mapping.get(part)
        return entry.get("registry_id") if entry else None

    def get_igem_id(self, part: str) -> Optional[str]:
        # Backward-compatible alias. In this project, registry IDs are iGEM IDs.
        return self.get_registry_id(part)

    def get_part_type(self, part: str) -> str:
        # Prefer the explicit part type from the mapping table when it exists.
        entry = self.mapping.get(part)
        if entry and entry.get("part_type"):
            return entry["part_type"]

        # Otherwise, infer the type from naming conventions used in GeneTech.
        if part.startswith("P") and part != "YFP":
            return "promoter"
        if part in {"AmtR", "AmeR", "HlYllR", "SrpR", "PhlF", "BM3R1", "Betl"}:
            return "cds"
        if part == "YFP":
            return "reporter"
        if part in {"A1", "F1", "H1", "S1", "P1", "B1", "E1"}:
            return "rbs"
        if part == "ECK120033737":
            return "terminator"
        return "unknown"

    def get_part_info(self, part: str) -> dict:
        # Return all known mapping data for a part. Use a copy so callers cannot
        # accidentally change the stored mapping.
        info = self.mapping.get(part, {}).copy()

        # Ensure every returned object has a part_type, even if the part was not
        # explicitly listed in the mapping table.
        info.setdefault("part_type", self.get_part_type(part))
        return info


class RegistryProvider:
    """
    Base class/interface for anything that can check a registry ID.

    Subclasses implement lookup(). That lets GeneTech support more registries
    later without rewriting the main database workflow.
    """

    name = "Registry"

    def lookup(self, registry_id: str) -> dict:
        # Subclasses must provide the real lookup behavior.
        raise NotImplementedError


class IGEMRegistryProvider(RegistryProvider):
    """
    Checks iGEM part IDs.

    By default this mostly uses the local KNOWN_PARTS dictionary below. Optional
    live web lookup support exists, but the GUI currently constructs
    GeneTechDatabase() with allow_web_lookup=False.
    """

    name = "iGEM Registry"

    # Local catalog of iGEM IDs known by this application. If a generated part
    # maps to one of these IDs, the database check can mark it as available
    KNOWN_PARTS = {
        "BBa_R0040": "TetR repressible promoter",
        "BBa_J23100": "Constitutive promoter",
        "BBa_B0034": "RBS (Elowitz 1999)",
        "BBa_E0030": "YFP reporter",
        "BBa_B0015": "Double terminator",
        "BBa_C0012": "LacI repressor",
        "BBa_K864500": "Tac promoter",
        "BBa_I0500": "AraC regulated promoter",
        "BBa_K1372001": "AmtR repressor",
        "BBa_K1372002": "AmeR repressor",
        "BBa_K1372003": "HlyIIR repressor",
        "BBa_K1372004": "SrpR repressor",
        "BBa_K1372005": "PhlF repressor",
        "BBa_K1372006": "BM3R1 repressor",
        "BBa_K1372007": "AmtR repressible promoter",
        "BBa_K1372008": "AmeR repressible promoter",
        "BBa_K1372009": "HlyIIR repressible promoter",
        "BBa_K1372010": "SrpR repressible promoter",
        "BBa_K1372011": "PhlF repressible promoter",
        "BBa_K1372012": "BM3R1 repressible promoter",
        "BBa_K1372013": "BetI repressible promoter",
        "BBa_K1372014": "BetI repressor",
    }

    def __init__(self, allow_web_lookup: bool = False, timeout: int = 3):
        # When False, IDs missing from KNOWN_PARTS are not checked online.
        self.allow_web_lookup = allow_web_lookup

        # Network timeout used only if live web lookup is enabled.
        self.timeout = timeout

        # In-memory cache avoids repeating the same lookup for the same ID.
        self.cache: Dict[str, dict] = {}

    def lookup(self, registry_id: str) -> dict:
        # Return cached result immediately if this ID was already checked.
        if registry_id in self.cache:
            return self.cache[registry_id]

        # Official iGEM URL format for a part ID.
        url = f"https://parts.igem.org/Part:{registry_id}"

        # Fast path: if the ID is in the local catalog, mark it as found.
        if registry_id in self.KNOWN_PARTS:
            result = {
                "found": True,
                "source": "local_catalog",
                "description": self.KNOWN_PARTS[registry_id],
                "url": url,
            }
        elif self.allow_web_lookup:
            # Optional live check: request the iGEM page and look for content
            # that suggests the part page exists.
            try:
                response = requests.get(url, timeout=self.timeout)
                result = {
                    "found": response.status_code == 200 and "part_name" in response.text.lower(),
                    "source": "web",
                    "description": "",
                    "url": url,
                }
            except requests.RequestException:
                # If the network fails, record that the web source was unreachable
                # instead of crashing the whole database check.
                result = {
                    "found": False,
                    "source": "web_unreachable",
                    "description": "",
                    "url": url,
                }
        else:
            # Normal GUI behavior for unknown IDs: do not go online, and report
            # that web lookup was disabled.
            result = {
                "found": False,
                "source": "web_lookup_disabled",
                "description": "",
                "url": url,
            }

        # Cache and return the result.
        self.cache[registry_id] = result
        return result


class BioPartsDBProvider(RegistryProvider):
    """
    Lightweight BioPartsDB-compatible adapter.

    This project currently maps parts through iGEM IDs, so this provider mainly
    exposes outbound links and a consistent integration point for future APIs.
    """

    name = "BioPartsDB"

    def lookup(self, registry_id: str) -> dict:
        # BioPartsDB uses the same kind of registry ID in the URL, but this
        # provider currently does not make a real API/web request. It only
        # supplies a useful outbound link for the report.
        url = f"https://biopartsdb.org/part/{registry_id}"
        return {
            "found": False,
            "source": "link_only",
            "description": "",
            "url": url,
        }


class GeneTechDatabase:
    """
    Integration layer used by the GUI and scripts to assess part availability
    and whether generated circuits are buildable from known registry parts.
    """

    def __init__(self, allow_web_lookup: bool = False, providers: Optional[List[RegistryProvider]] = None):
        # Create the mapper that translates GeneTech part names to registry IDs.
        self.mapper = PartMapper()

        # Use custom providers if supplied; otherwise use the default iGEM and
        # BioPartsDB providers.
        self.providers = providers or [
            IGEMRegistryProvider(allow_web_lookup=allow_web_lookup),
            BioPartsDBProvider(),
        ]

    def check_circuits_file(self, filename: Path | str = CIRCUITS_FILE) -> List[dict]:
        # Compatibility helper for older code that only wants a flat list of
        # availability results, not the full report.
        report = self.analyze_circuits_file(filename)
        return [entry["availability"] for entry in report["parts"]]

    def analyze_circuits_file(self, filename: Path | str = CIRCUITS_FILE) -> dict:
        # Normalize the filename into a Path object so we can use Path methods.
        filename = Path(filename)

        # Stop early with a clear error if no circuit file has been generated.
        if not filename.exists():
            raise FileNotFoundError(f"{filename} not found")

        # Parse circuits.txt into structured circuit objects.
        circuits = self._parse_circuits_file(filename)

        # Collect every unique part across every circuit. A set removes
        # duplicates, and sorted() makes reports stable and easier to read.
        unique_parts = sorted({part for circuit in circuits for part in circuit["parts"]})

        # Resolve each part into registry information and availability status.
        part_entries = [self._resolve_part(part) for part in unique_parts]

        # Build a quick lookup table so circuit reports can reuse resolved parts.
        part_lookup = {entry["part"]: entry for entry in part_entries}

        # Build the per-circuit section of the report.
        circuit_reports = []
        for circuit in circuits:
            # A circuit is blocked if any part used by that circuit is unavailable.
            missing = [part_lookup[part] for part in circuit["parts"] if not part_lookup[part]["availability"]["available"]]
            circuit_reports.append(
                {
                    "circuit_index": circuit["circuit_index"],
                    "parts": [part_lookup[part] for part in circuit["parts"]],
                    "buildable": len(missing) == 0,
                    "missing_parts": missing,
                }
            )

        # Build high-level counts for the GUI and the top of the JSON report.
        summary = {
            "total_parts": len(part_entries),
            "available_parts": sum(1 for entry in part_entries if entry["availability"]["available"]),
            "missing_parts": sum(1 for entry in part_entries if not entry["availability"]["available"]),
            "total_circuits": len(circuit_reports),
            "buildable_circuits": sum(1 for report in circuit_reports if report["buildable"]),
            "all_circuits_buildable": all(report["buildable"] for report in circuit_reports) if circuit_reports else False,
        }

        # The full report includes metadata, summary numbers, detailed part
        # results, and detailed circuit results.
        report = {
            "generated_at": datetime.now().isoformat(timespec="seconds"),
            "source_file": str(filename),
            "providers": [provider.name for provider in self.providers],
            "summary": summary,
            "parts": part_entries,
            "circuits": circuit_reports,
        }

        # Save the report to disk and include the saved file path in the report.
        report["report_file"] = self._save_report(report)
        return report

    def assess_buildability(self, filename: Path | str = CIRCUITS_FILE) -> bool:
        # Small helper that returns only True/False for whether every circuit is
        # buildable, instead of returning the full analysis.
        return self.analyze_circuits_file(filename)["summary"]["all_circuits_buildable"]

    def _resolve_part(self, part: str) -> dict:
        # Get mapping data for this GeneTech part name.
        part_info = self.mapper.get_part_info(part)

        # Pull out the important mapping fields.
        registry_id = part_info.get("registry_id")
        part_type = part_info.get("part_type", "unknown")
        description = part_info.get("description", "")

        # If there is no registry ID, the app cannot check this part in iGEM or
        # BioPartsDB, so it is marked unavailable because it is unmapped.
        if not registry_id:
            availability = PartAvailability(
                part=part,
                part_type=part_type,
                registry_id=None,
                registry_name=None,
                available=False,
                source="mapping",
                description=description,
                reason="No registry mapping",
            )
            provider_results = []
        else:
            # Store the raw result from every provider, even if only one provider
            # eventually determines the final availability.
            provider_results = []

            # This stays None until a provider successfully finds the part.
            availability = None

            # Ask each configured provider about the same registry ID.
            for provider in self.providers:
                lookup = provider.lookup(registry_id)

                # Normalize provider-specific output into one common shape.
                provider_result = {
                    "registry_name": provider.name,
                    "registry_id": registry_id,
                    "available": lookup.get("found", False),
                    "source": lookup.get("source", ""),
                    "description": lookup.get("description", ""),
                    "url": lookup.get("url", ""),
                }
                provider_results.append(provider_result)

                # The first provider that finds the part becomes the final
                # availability source shown to the GUI.
                if provider_result["available"] and availability is None:
                    availability = PartAvailability(
                        part=part,
                        part_type=part_type,
                        registry_id=registry_id,
                        registry_name=provider.name,
                        available=True,
                        source=provider_result["source"],
                        description=provider_result["description"] or description,
                        url=provider_result["url"],
                    )

            # If no provider found the part, mark it unavailable but keep the
            # primary provider's URL/source so the report still explains where
            # the lookup tried to go.
            if availability is None:
                primary = provider_results[0] if provider_results else {}
                availability = PartAvailability(
                    part=part,
                    part_type=part_type,
                    registry_id=registry_id,
                    registry_name=primary.get("registry_name"),
                    available=False,
                    source=primary.get("source", "registry"),
                    description=description,
                    url=primary.get("url", ""),
                    reason="Not found in configured registries",
                )

        # Return one report entry for this part. It includes both the final
        # availability decision and the raw provider-by-provider results.
        return {
            "part": part,
            "part_type": part_type,
            "registry_id": registry_id,
            "description": description,
            "availability": availability.to_legacy_dict(),
            "providers": provider_results,
        }

    def _parse_circuits_file(self, filename: Path) -> List[dict]:
        # Read the generated circuits text from disk.
        content = filename.read_text()

        # Each circuit is separated by a row of asterisks in circuits.txt.
        blocks = [block.strip() for block in content.split("*******************") if block.strip()]

        # This will become a list of parsed circuit dictionaries.
        circuits = []

        for index, block in enumerate(blocks, start=1):
            # lines keeps the original useful circuit lines; parts stores the
            # unique biological parts found in this one circuit.
            lines = []
            parts = set()

            # Process the circuit block one line at a time.
            for raw_line in block.splitlines():
                line = raw_line.strip()

                # Skip empty lines, separator/decorative lines, and title lines.
                if not line or line.startswith("*") or line.startswith("Genetic Circuit"):
                    continue

                # Keep the actual circuit line for the report.
                lines.append(line)

                # Extract biological part names from this line and add them to
                # the circuit's part set.
                parts.update(self._extract_parts_from_line(line))

            # Only add blocks that contained at least one real circuit line.
            if lines:
                circuits.append(
                    {
                        "circuit_index": index,
                        "lines": lines,
                        "parts": sorted(parts),
                    }
                )

        return circuits

    def _extract_parts_from_line(self, line: str) -> Iterable[str]:
        # Start with the raw circuit notation line.
        cleaned = line

        # Replace wiring/logic symbols with spaces so only words remain.
        for token in ["->", "|", "(", ")", "-", "^"]:
            cleaned = cleaned.replace(token, " ")

        # Words that should not be treated as biological parts.
        ignored = {"and", "or", "not", "END"}

        # Split the cleaned line into candidate part names.
        for word in cleaned.split():
            candidate = word.strip()

            # Ignore blank values, one-character symbols, and pure numbers.
            if not candidate or len(candidate) <= 1 or candidate.isdigit():
                continue

            # Ignore reserved words that are not genetic parts.
            if candidate in ignored:
                continue

            # Yield one extracted part name back to the parser.
            yield candidate

    def _save_report(self, report: dict) -> str:
        # Use the current date/time so every database check gets a unique file.
        timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")

        # Example filename: igem_report_20260511_152604.json.
        report_path = REPORTS_DIR / f"igem_report_{timestamp}.json"

        # Write pretty JSON so humans can read the report easily.
        report_path.write_text(json.dumps(report, indent=2))

        # Return the path as text so the GUI can display it.
        return str(report_path)


def check_current_circuits() -> List[dict]:
    # Convenience function for scripts: check the default circuits.txt file and
    # return the older flat availability list.
    return GeneTechDatabase().check_circuits_file()
